name: teflink_core
description: Centralized core for teFlink framework.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  teflink_console:
    path: ../console
  teflink_dot_env:
    path: ../dot_env
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
